print("I like to play hockey")
print("I like my two dogs, Juno and Kona")
print("I like video games")
print("I like to throw around a frisbee")
print("I like to play board games with my family")
print("I like to code")
print("I like the study of the human body")
print("I like astronomy")
print("I like to listen to music")
print("I like hanging out with friends")